### ISSUE TITLE
Old config not work

### ISSUE THREAD

**Issue by GlobusOk** [Rosstail/Karma#25]
since 04/04/2022 I have not updated the application, a couple of days I updated all the plugins to the latest versions. karma plugin doesn't want to interact with my config. I can't figure out what's wrong.

**Comment by GlobusOk** [comment]
mysql:
  active: false
  host: "localhost"
  port: 3306
  database: "database_name"
  username: "root"
  password: ""

data-save-delay: 300

general:
  lang: "ru_RU"
  #decimal-display: 0 #The number of digits behind Karma amounts on display (does not affect storage or calculations)
  title: #Duration of the title in ticks (20ticks = 1 second)
    fade-in: 1
    stay: 20
    fade-out: 1
  use-worldguard: false #works only for Worldguard 7+
  datetime-format: "yyyy-MM-dd HH:mm:ss"
  countdown-format: "{dd} {HH}:{mm}:{ss}" #use dd, d, hh, h, mm, m, ss, s between {} without cap.

karma:
  default:     0
  minimum: -9999
  maximum:  9999

worlds:
  enable: false #if enabled, only the worls listed below will be used
  black-list: false #if true, the worlds on the list will not be used
  worlds:
    - world

overtime:
  enable: true
  loops:
    #loopName: #name it however you want
    #  timers:
    #    first: <long> # First timer, generally longer or equal to the NEXT.
    #    next: <long>  # Timer after first occurence. Generally shorter or equal
    #  requirements:
    #    karma:
    #      minimum: <double> #Ignored if empty
    #      maximum: <double> #ignored if empty
    #    online: <boolean> #true by default
    #    offline: <boolean> #false by default
    #  amount: <double> #0 by default. If offline is true, applies for every delays reached
    #  commands: <String[]> #ignored if empty. If offline is true, applies only once on reconnection.
    online-citizen:
      timers:
        first: 3600
        next: 1800
      requirements:
        karma:
          minimum: 500
      amount: -50
      commands:
        - "bc Removed 50 karma to online %player% (online only, hourly then mid-hourly)."
    offline-citizen:
      timers:
        first: 43200
      requirements:
        online: false
        offline: true
        karma:
          minimum: 500
      amount: -250
      commands:
        - "bc Removed %karma_player_diff_karma% karma to %player% (offline only, daily)."
    online-criminal:
      timers:
        first: 3600
        next: 1800
      requirements:
        karma:
          maximum: -1500
      amount: 25
      commands:
        - "bc Added 25 karma to %player% (online only, hourly then mid-hourly)."
    offline-criminal:
      timers:
        first: 43200
      requirements:
        online: false
        offline: true
        karma:
          maximum: -1500
      amount: 125
      commands:
        - "bc Added %karma_player_diff_karma% karma to %player% (offline only, daily)."

tiers:
  none-display: "&f[&8None&f]&r"
  none-short-display: "&f"
  list:
    evil:
      display: "&0[Гроза космоса]"
      short-display: "&4"
      minimum: -9999
      maximum: -7000
      score:
        vile: 50
        mean: 35
        rude: 20
        neutral: -10
        kind: -30
        good: -40
        pure: -50
        best: -80
      commands:
        join-commands:
          - "broadcast &f%player% is now the most wanted %karma_player_tier_display% &r."
        join-on-down-commands:
          - "player %msg-title% {#FF0000}&lWANTED %msg-subtitle%&cEverybody is now trying to kill you."
    vile:
      display: "&5[Головорез]"
      short-display: "&4"
      minimum: -6999
      maximum: -4000
      score:
        evil: 45
        mean: 30
        rude: 15
        neutral: -15
        kind: -40
        good: -50
        pure: -60
        best: -90
      commands:
        join-commands:
          - "broadcast &f%player% is now the most wanted %karma_player_tier_display% &r."
        join-on-down-commands:
          - "player %msg-title% {#FF0000}&lWANTED %msg-subtitle%&cEverybody is now trying to kill you."
        killed-commands:
          sheriff:
            - "jail %victim% jail %karma_victim_karma%"
            - "karma set %victim% -3000"
            - "broadcast %victim% &ahas been arrested for %karma_victim_previous_karma% minutes by %attacker% !"
    mean:
      display: "&4[Пират]"
      short-display: "&4"
      minimum: -3999
      maximum: -2000
      score:
        evil: 55
        vile: 40
        rude: 20
        neutral: -15
        kind: -45
        good: -55
        pure: -65
        best: -95
      commands:
        join-commands:
          - "broadcast &f%player% is now the most wanted %karma_player_tier_display% &r."
        join-on-down-commands:
          - "player %msg-title% {#FF0000}&lWANTED %msg-subtitle%&cEverybody is now trying to kill you."
        killed-commands:
    rude:
      display: "&c[Преступник]"
      short-display: "&5"
      minimum: -1999
      maximum: -51
      score:
        evil: 60
        vile: 55
        mean: 40
        neutral: -20
        kind: -50
        good: -65
        pure: -80
        best: -100
      commands:
        join-commands:
          - "player message &fYou are now a filthy %karma_player_tier% &r."
          - "player me &5is now in the dark side of the law."
        join-on-down-commands:
          - "player message &bThe police is now hunting you."
        join-on-up-commands:
          - "playermessage &aKeep a low profile."
        killed-commands:
    neutral:
      display: "&7[Исследователь]"
      short-display: "&f"
      minimum: -50
      maximum: 49
      score:
        evil: 120
        vile: 100
        mean: 80
        rude: 70
        kind: -20
        good: -60
        pure: -80
        best: -100
      commands:
        join-commands:
          - "player%msg% &fВаш статус %karma_player_tier_display% &r."
    kind:
      display: "&b[Охотник]"
      short-display: "&f"
      minimum: 50
      maximum: 2000
      score:
        evil: 100
        vile: 80
        mean: 65
        rude: 50
        neutral: -20
        good: -40
        pure: -55
        best: -60
      commands:
        join-commands:
          - "player%msg% &fВаш статус %karma_player_tier_display% &r."
    good:
      display: "&3[Защитник]"
      short-display: "&a"
      minimum: 2001
      maximum: 4000
      score:
        evil: 95
        vile: 65
        mean: 55
        rude: 45
        neutral: -25
        kind: -15
        pure: -40
        best: -55
      commands:
        join-commands:
          - "player %msg% &fВаш статус %karma_player_tier_display% &r."
        join-on-up-commands:
          - "player%msg% &bТы теперь можешь помочь военным."
        join-on-down-commands:
          - "player %msg% &bYou have been demoted from the police forces."
        killed-commands:
          commands:
            - "attacker %msg% You killed a %karma_victim_tier_display%, you got %karma_attacker_diff_karma% karma"
    pure:
      display: "&a[Рейнжер]"
      short-display: "&6"
      minimum: 4001
      maximum: 7000
      score:
        evil: 90
        vile: 60
        mean: 50
        rude: 40
        neutral: -35
        kind: -15
        good: -30
        best: -45
      commands:
        join-commands:
          - "player %msg% &fYour wanted level is now %karma_player_tier_display% &r."
        join-on-up-commands:
          - "player %msg% &bYou are got promoted from %karma_player_previous_tier_display%."
        killed-commands:
          commands:
            - "broadcast %victim% has been assassinated by %attacker% with %karma_attacker_previous_karma% karma before the act."
          criminal:
            - "victim %msg% %attacker% was in Criminal tier when he killed you."
    best:
      display: "&2[Герой]"
      short-display: "&4"
      minimum: 7001
      maximum: 9999
      score:
        evil: 85
        vile: 55
        mean: 45
        rude: 35
        neutral: -100
        kind: -30
        good: -50
        pure: -80
      commands:
        join-commands:
          - "broadcast &f%player% is now the most wanted %karma_player_tier_display% &r."
        join-on-down-commands:
          - "player %msg-title% {#FF0000}&lWANTED
          %msg-subtitle%&cEverybody is now trying to kill you."
        killed-commands:
          sheriff:
            - "jail %victim% jail %karma_victim_karma%"
            - "karma set %victim% -3000"
            - "broadcast %victim% &ahas been arrested for %karma_victim_previous_karma% minutes by %attacker% !" 

times:
  use-both-system-and-worlds-time: "NONE" #can be replaced by WORLDS, SYSTEM and BOTH or NONE
  #NONE Doesn't check time
  #WORLDS Check only the worlds-time
  #SYSTEM Check only the server/system time
  #BOTH check WORLDS AND SYSTEM. both must be TRUE.
  worlds-times: #use the time where the attacker / killer is You can add all the time-X you want with custom name
    day:
      start-time: "09:00"
      end-time: "20:00"
      rate: 100
    dusk:
      start-time: "20:00"
      end-time: "22:00"
      rate: 66
    night:
      start-time: "22:00"
      end-time: "01:00"
      rate: 30
  system-times: #use the server real life time. You can add all the time-X you want, with custom name
    morning:
      start-time: "08:00"
      end-time: "12:59"
      rate: 100
    afternoon:
      start-time: "13:00"
      end-time: "21:00"
      rate: 30

pvp:
  # You can make your own expression, any error will lead to a result of 0.
  hit-reward-expression: "(-1 * (%karma_victim_karma% + 200) / 50)"
  kill-reward-expression: "(-1 * (%karma_victim_karma% + 200) / 10)"
  messages-delay:
    hit: 5
    kill: 10
  wanted: #if a player attacks another one, everybody can strike him back without karma changes (unless if the defender is wanted too)
    enable: true
    countdown-on-disconnect: true
    #%karma_player_wanted_time% use the highest amount between the player's wanted time and the actual timestamp.
    duration: "(%karma_player_wanted_time% + (300 * 1000))" #delay in milliseconds.
    max-duration: "(%timestamp% + (3600 * 1000))"
    conditions:
      on-karma-gain: false
      on-karma-unchanged: false
      on-karma-loss: true
      refresh: true
    cancel-karma-change:
      wanted:
        on-karma-gain: true
        on-karma-loss: false
      innocent:
        on-karma-gain: false
        on-karma-loss: true

entities:
  #default entities names
  ENDERMITE:
    kill-karma-reward:   5
  Silverfish:
    kill-karma-reward:   7
  BEE:
    kill-karma-reward:  15
  BABY_ZOMBIE:
    kill-karma-reward:  15
  Zombie_villager:
    kill-karma-reward:  100
  Snowman:
    kill-karma-reward:  8
  MAGMA_CUBE:
    kill-karma-reward:  10
  Husk:
    kill-karma-reward:  60
    
  #renamed entities
  Urban:
    kill-karma-reward:   5
shops:
  list:
    first:
      display: "&aFirst"
      description: "&fFirst Shop. Usable by player"
      price: 1000.0
      cost-reset-overtime: false
      min-karma: 1000
      sender: PLAYER #PLAYER / CONSOLE / BOTH
      commands:
        - "bc %player% bought the first item from karma shop !"
    second:
      display: "&9First"
      description: "&fSecond Shop. Not usable by player"
      price: -500.0
      cost-reset-overtime: false
      max-karma: -500
      sender: CONSOLE #PLAYER / CONSOLE / BOTH
      commands:
        - "bc %player% bought the second item from karma shop !"

**Comment by Rosstail** [comment]
Did you also update your lang file (since you asked on discord)

**Comment by GlobusOk** [comment]
I deleted the config folder so that the plugin creates new ones. After that, I replaced only the lines with the names of the ranks of karma and their meaning.

**Comment by Rosstail** [comment]
Hi there. I have fixed your config.yml, it should work perfectly now.

```yaml
mysql:
    active: false
    host: "localhost"
    port: 3306
    database: "database_name"
    username: "root"
    password: ""

data-save-delay: 300

general:
  lang: "ru_RU"
  #decimal-display: 0 #The number of digits behind Karma amounts on display (does not affect storage or calculations)
  title: #Duration of the title in ticks (20ticks = 1 second)
    fade-in: 1
    stay: 20
    fade-out: 1
  use-worldguard: false #works only for Worldguard 7+
  datetime-format: "yyyy-MM-dd HH:mm:ss"
  countdown-format: "{dd} {HH}:{mm}:{ss}" #use dd, d, hh, h, mm, m, ss, s between {} without cap.

karma:
  default: 0
  minimum: -9999
  maximum: 9999

worlds:
  enable: false #if enabled, only the worls listed below will be used
  black-list: false #if true, the worlds on the list will not be used
  worlds:
    - world

overtime:
  enable: true
  loops:
    #loopName: #name it however you want
    # timers:
    # first: # First timer, generally longer or equal to the NEXT.
    # next: # Timer after first occurence. Generally shorter or equal
    # requirements:
    # karma:
    # minimum: #Ignored if empty
    # maximum: #ignored if empty
    # online: #true by default
    # offline: #false by default
    # amount: #0 by default. If offline is true, applies for every delays reached
    # commands: <String[]> #ignored if empty. If offline is true, applies only once on reconnection.
    online-citizen:
      timers:
        first: 3600
        next: 1800
      requirements:
        karma:
          minimum: 500
      amount: -50
      commands:
            - "bc Removed 50 karma to online %player% (online only, hourly then mid-hourly)."
    offline-citizen:
      timers:
        first: 43200
      requirements:
        online: false
        offline: true
      karma:
        minimum: 500
      amount: -250
      commands:
        - "bc Removed %karma_player_diff_karma% karma to %player% (offline only, daily)."
    online-criminal:
      timers:
        first: 3600
        next: 1800
      requirements:
        karma:
          maximum: -1500
      amount: 25
      commands:
        - "bc Added 25 karma to %player% (online only, hourly then mid-hourly)."
    offline-criminal:
      timers:
        first: 43200
      requirements:
        online: false
        offline: true
      karma:
        maximum: -1500
      amount: 125
      commands:
        - "bc Added %karma_player_diff_karma% karma to %player% (offline only, daily)."

tiers:
  none-display: "&f[&8None&f]&r"
  none-short-display: "&f"
  list:
    evil:
      display: "&0[Гроза космоса]"
      short-display: "&4"
      minimum: -9999
      maximum: -7000
      score:
        vile: 50
        mean: 35
        rude: 20
        neutral: -10
        kind: -30
        good: -40
        pure: -50
        best: -80
      commands:
        join-commands:
          - "broadcast &f%player% is now the most wanted %karma_player_tier_display% &r."
        join-on-down-commands:
          - "player %msg-title% {#FF0000}&lWANTED %msg-subtitle%&cEverybody is now trying to kill you."
    vile:
      display: "&5[Головорез]"
      short-display: "&4"
      minimum: -6999
      maximum: -4000
      score:
        evil: 45
        mean: 30
        rude: 15
        neutral: -15
        kind: -40
        good: -50
        pure: -60
        best: -90
      commands:
        join-commands:
          - "broadcast &f%player% is now the most wanted %karma_player_tier_display% &r."
        join-on-down-commands:
          - "player %msg-title% {#FF0000}&lWANTED %msg-subtitle%&cEverybody is now trying to kill you."
        killed-commands:
          sheriff:
            - "jail %victim% jail %karma_victim_karma%"
            - "karma set %victim% -3000"
            - "broadcast %victim% &ahas been arrested for %karma_victim_previous_karma% minutes by %attacker% !"
    mean:
      display: "&4[Пират]"
      short-display: "&4"
      minimum: -3999
      maximum: -2000
      score:
        evil: 55
        vile: 40
        rude: 20
        neutral: -15
        kind: -45
        good: -55
        pure: -65
        best: -95
      commands:
        join-commands:
          - "broadcast &f%player% is now the most wanted %karma_player_tier_display% &r."
        join-on-down-commands:
         - "player %msg-title% {#FF0000}&lWANTED %msg-subtitle%&cEverybody is now trying to kill you."
    rude:
      display: "&c[Преступник]"
      short-display: "&5"
      minimum: -1999
      maximum: -51
      score:
        evil: 60
        vile: 55
        mean: 40
        neutral: -20
        kind: -50
        good: -65
        pure: -80
        best: -100
      commands:
        join-commands:
          - "player message &fYou are now a filthy %karma_player_tier% &r."
          - "player me &5is now in the dark side of the law."
        join-on-down-commands:
          - "player message &bThe police is now hunting you."
        join-on-up-commands:
          - "playermessage &aKeep a low profile."
    neutral:
      display: "&7[Исследователь]"
      short-display: "&f"
      minimum: -50
      maximum: 49
      score:
        evil: 120
        vile: 100
        mean: 80
        rude: 70
        kind: -20
        good: -60
        pure: -80
        best: -100
      commands:
        join-commands:
          - "player%msg% &fВаш статус %karma_player_tier_display% &r."
    kind:
      display: "&b[Охотник]"
      short-display: "&f"
      minimum: 50
      maximum: 2000
      score:
        evil: 100
        vile: 80
        mean: 65
        rude: 50
        neutral: -20
        good: -40
        pure: -55
        best: -60
      commands:
        join-commands:
          - "player%msg% &fВаш статус %karma_player_tier_display% &r."
    good:
      display: "&3[Защитник]"
      short-display: "&a"
      minimum: 2001
      maximum: 4000
      score:
        evil: 95
        vile: 65
        mean: 55
        rude: 45
        neutral: -25
        kind: -15
        pure: -40
        best: -55
      commands:
        join-commands:
          - "player %msg% &fВаш статус %karma_player_tier_display% &r."
        join-on-up-commands:
          - "player%msg% &bТы теперь можешь помочь военным."
        join-on-down-commands:
          - "player %msg% &bYou have been demoted from the police forces."
        killed-commands:
          commands:
            - "attacker %msg% You killed a %karma_victim_tier_display%, you got %karma_attacker_diff_karma% karma"
    pure:
      display: "&a[Рейнжер]"
      short-display: "&6"
      minimum: 4001
      maximum: 7000
      score:
        evil: 90
        vile: 60
        mean: 50
        rude: 40
        neutral: -35
        kind: -15
        good: -30
        best: -45
      commands:
        join-commands:
          - "player %msg% &fYour wanted level is now %karma_player_tier_display% &r."
        join-on-up-commands:
          - "player %msg% &bYou are got promoted from %karma_player_previous_tier_display%."
        killed-commands:
          commands:
            - "broadcast %victim% has been assassinated by %attacker% with %karma_attacker_previous_karma% karma before the act."
          criminal:
            - "victim %msg% %attacker% was in Criminal tier when he killed you."
    best:
      display: "&2[Герой]"
      short-display: "&4"
      minimum: 7001
      maximum: 9999
      score:
        evil: 85
        vile: 55
        mean: 45
        rude: 35
        neutral: -100
        kind: -30
        good: -50
        pure: -80
      commands:
        join-commands:
          - "broadcast &f%player% is now the most wanted %karma_player_tier_display% &r."
        join-on-down-commands:
          - "player %msg-title% {#FF0000}&lWANTED %msg-subtitle%&cEverybody is now trying to kill you."
        killed-commands:
          sheriff:
            - "jail %victim% jail %karma_victim_karma%"
            - "karma set %victim% -3000"
            - "broadcast %victim% &ahas been arrested for %karma_victim_previous_karma% minutes by %attacker% !"

times:
  use-both-system-and-worlds-time: "NONE" #can be replaced by WORLDS, SYSTEM and BOTH or NONE
  #NONE Doesn't check time
  #WORLDS Check only the worlds-time
  #SYSTEM Check only the server/system time
  #BOTH check WORLDS AND SYSTEM. both must be TRUE.
  worlds-times: #use the time where the attacker / killer is You can add all the time-X you want with custom name
    day:
      start-time: "09:00"
      end-time: "20:00"
      rate: 100
    dusk:
      start-time: "20:00"
      end-time: "22:00"
      rate: 66
    night:
      start-time: "22:00"
      end-time: "01:00"
      rate: 30
  system-times: #use the server real life time. You can add all the time-X you want, with custom name
    morning:
      start-time: "08:00"
      end-time: "12:59"
      rate: 100
    afternoon:
      start-time: "13:00"
      end-time: "21:00"
      rate: 30

pvp:
#You can make your own expression, any error will lead to a result of 0.
  hit-reward-expression: "(-1 * (%karma_victim_karma% + 200) / 50)"
  kill-reward-expression: "(-1 * (%karma_victim_karma% + 200) / 10)"
  messages-delay:
    hit: 5
    kill: 10
  wanted: #if a player attacks another one, everybody can strike him back without karma changes (unless if the defender is wanted too)
    enable: true
    countdown-on-disconnect: true
    #%karma_player_wanted_time% use the highest amount between the player's wanted time and the actual timestamp.
    duration: "(%karma_player_wanted_time% + (300 * 1000))" #delay in milliseconds.
    max-duration: "(%timestamp% + (3600 * 1000))"
    conditions:
      on-karma-gain: false
      on-karma-unchanged: false
      on-karma-loss: true
      refresh: true
    cancel-karma-change:
      wanted:
        on-karma-gain: true
        on-karma-loss: false
      innocent:
        on-karma-gain: false
        on-karma-loss: true

entities:
  messages-delay:
    hit: 5
    kill: 10
  list:
    #default entities names
    ENDERMITE:
        kill-karma-reward: 5
    Silverfish:
        kill-karma-reward: 7
    BEE:
        kill-karma-reward: 15
    BABY_ZOMBIE:
        kill-karma-reward: 15
    Zombie_villager:
        kill-karma-reward: 100
    Snowman:
        kill-karma-reward: 8
    MAGMA_CUBE:
        kill-karma-reward: 10
    Husk:
        kill-karma-reward: 60
    #renamed entities
    Urban:
        kill-karma-reward: 5

shops:
  cost-reset-overtime: false
  list:
    first:
      display: "&aFirst"
      description: "&fFirst Shop. Usable by player"
      price: 1000.0
      cost-reset-overtime: false
      min-karma: 1000
      send-by: PLAYER #PLAYER / CONSOLE / BOTH
      commands:
        - "bc %player% bought the first item from karma shop !"
    second:
      display: "&9First"
      description: "&fSecond Shop. Not usable by player"
      price: -500.0
      cost-reset-overtime: false
      max-karma: -500
      send-by: CONSOLE #PLAYER / CONSOLE / BOTH
      commands:
        - "bc %player% bought the second item from karma shop !"
```
