### ISSUE TITLE
pvp karma not working

### ISSUE THREAD

**Issue by socksiwthacoffeecup** [Rosstail/Karma#9]
For some reason I can't get PVP to work on my server, though I could just be missing how to enable it? I've edited config files before but is there something specific I need to change under pvp to get it to work?

**Comment by Rosstail** [comment]
Hi, which verison of karma do you use and what is your config.yml ?

**Comment by socksiwthacoffeecup** [comment]
I'm using 1.5.4 and my config.yml is below. I could just be missing something I appreciate the quick response!!

```
 mysql:
  active: false
  host: "localhost"
  port: 3306
  database: "database_name"
  username: "root"
  password: ""

data-save-delay: 300

general:
  lang: "en_EN"
  decimal-number-to-show: 2
  delay-between-hit-messages: 5
  delay-between-kill-messages: 10
  use-worldguard: false #works only for Worldguard 7+
  use-action-bar-on-actions: true
  date-time-format: "yyyy-MM-dd HH:mm:ss"

karma:
  default:       0
  minimum: -300000
  maximum:  300000

world-fight-system:
  enable: false
  black-list: false
  worlds:
    - world

overtime: #Useful for GTA Wanted Level. Reset when karma changes from fights and commands.
  active: false
  first-delay: 60 #first occurrence in seconds after a karma change.
  next-delay: 10 #every occurrences in seconds after the first one
  values:
    decrease:
      value: 5
      limit: 0
    increase:
      value: 5
      limit: 0

tiers:
  tier-3:
    display: "&f[&4Villain&f]&r"
    minimum: -300000
    maximum: -150000
    join-commands:
      - "<MESSAGE> &6<PLAYER>&r, you are now a <TIER> &r!"
      - "me &8is the baddest <TIER>."
      - "me another command"
      - "<@>me command from console"
    killed-commands:
      - "<@>jail <PLAYER> gta-jail 3600"
      - "<@>broadcast <PLAYER> &ahas been arrested !"
  tier-2:
    display: "&f[&cCriminal&f]&r"
    minimum: -149999
    maximum:  -30000
    join-commands:
      - "<MESSAGE> &6<PLAYER>&r, you are now a <TIER> &r!"
      - "me &cis really bad."
      - "me &cseriously guys."
    join-on-up-commands:
      - "me I'm not the most wanted anymore... Better !"
    join-on-down-commands:
      - "me I've made a big raberry today, ahah !"
    killed-commands:
      - "<@>jail <PLAYER> gta-jail 1800"
      - "<@>broadcast <PLAYER> &ahas been arrested !"
  tier-1:
    display: "&f[&eThug&f]&r"
    minimum:  -29999
    maximum:   -5000
    join-commands:
      - "<MESSAGE> &6<PLAYER>&r, you are now a <TIER> &r!"
      - "me &eis not gentle."
    join-on-up-commands:
      - "me But I'm better than some guys !"
    join-on-down-commands:
      - "me But this wasn't me !"
  tier_0:
    display: "&f[&7Civilian&f]&r"
    minimum:   -4999
    maximum:    4999
    join-commands:
      - "<MESSAGE> &6<PLAYER>&r, you are now a <TIER> &r!"
      - "me &7is the neutral neutral alignment."
      - "<@>me &6<PLAYER> &aHey ! Your karma is &6<KARMA> &r!"
    join-on-up-commands:
      - "me I'm not a thug anymore !"
    join-on-down-commands:
      - "me I've made some mistakes, back to normal."
  tier+1:
    display: "&f[&aVigilante&f]&r"
    minimum:    5000
    maximum:   29999
    join-commands:
      - "<MESSAGE> &6<PLAYER>&r, you are now a <TIER> &r!"
      - "me &ais now a good guy who likes Streets of Rage games serie."
      - "me &ais a test, it will be sent by player."
      - "<@>me must not be sent by player but by console."
    join-on-up-commands:
      - "me I'm a good guy !"
    join-on-down-commands:
      - "me I just loss my sheriff star..."
  tier+2:
    display: "&f[&bSheriff&f]&r"
    minimum:   30000
    maximum:  149999
    join-commands:
      - "<MESSAGE> &6<PLAYER>&r, you are now a <TIER> &r!"
      - "me &bhas right to kill anyone who messes them, yes."
    join-on-up-commands:
      - "me I AM THE LAW ! DROP YOU WEAPONS !"
    join-on-down-commands:
      - "me Heroes ? Nah."
  tier+3:
    display: "&f[&6Hero&f]&r"
    minimum:  150000
    maximum:  300000
    join-commands:
      - "<MESSAGE> &6<PLAYER>&r, you are now a <TIER> &r!"
      - "me &6is the hero !"
      - "me &6another command !"
      - "<@>me You can create an infinite amount of join-commands and tiers !"

times:
  use-both-system-and-worlds-time: "NONE" #can be replaced by WORLDS, SYSTEM and BOTH or NONE
  #NONE Doesn't check time
  #WORLDS Check only the worlds-time
  #SYSTEM Check only the server/system time
  #BOTH check WORLDS AND SYSTEM. both must be TRUE.
  worlds-times: #use the time where the attacker / killer is You can add all the time-X you want with custom name
    time-1:
      start-time: "09:00"
      end-time: "20:00"
      rate: 100
    time-2:
      start-time: "20:00"
      end-time: "22:00"
      rate: 66
    time-3:
      start-time: "22:00"
      end-time: "01:00"
      rate: 30
  system-times: #use the server real life time. You can add all the time-X you want, with custom name
    time-1:
      start-time: "08:00"
      end-time: "12:00"
      rate: 100
    time-2:
      start-time: "13:00"
      end-time: "21:00"
      rate: 30

pvp:
  # You can make your own expression
  hit-reward-expression:  (-1 * (<VICTIM_KARMA> + 3000) / 50)
  kill-reward-expression:  (-1 * (<VICTIM_KARMA> + 3000) / 10)
  crime-time: #if a player attacks another one, everybody can attack him back without karma changes (unless if the defender is an agressor)
    enable: true
    delay: 300 #delay in second that a player is an agressor.
    # Enable or not the karma change if the defender won/less some karma or stay at the same karma.
    # Useful for avoid messages in a future update too.
    active-on-up: true
    active-on-still: false
    active-on-down: false
  #Sends a message to <attacker> when hitting / killing another player. You can use <attacker>, <attackerKarma>, <victim> and <victimKarma>.
  hit-message-on-karma-increase: "&aThat scum will not escape from that !"
  kill-message-on-karma-increase: "&bThat bastard is now finished !"
  hit-message-on-karma-decrease: "&cYou attack honest people !"
  kill-message-on-karma-decrease: "&cSonovabitch !"

entities:
  Bee:
    hit-karma-reward:      1
    hit-message: "Run villager, RUN !!!"
    kill-karma-reward:     3
    kill-message: "<ATTACKER> : You captured a bee ! &5*Animal Crossing MLG music* &a<OLD_KARMA> + <VALUE> = <KARMA>"
  Cat:
    hit-karma-reward:    -10
    hit-message: "&cYou DARE put a hand on your Master ?!!"
    kill-karma-reward:   -76
    kill-message: "&4&lWILFRIIIIIIIED !!!"
  EnderDragon:
    hit-karma-reward:      1
    hit-message: "&aKEEP GOING"
    kill-karma-reward: 10000
    kill-message: "&6&lYou did it ! You finally did it !"
  Skeleton:
    hit-karma-reward:      1
    kill-karma-reward:   100
  SkeletonHorse:
    hit-karma-reward:      1
    kill-karma-reward:   100
  TraderLlama:
    hit-karma-reward:    -11
    kill-karma-reward:  -356
  Villager:
    hit-karma-reward:    -34
    kill-karma-reward:  -651
  Wolf:
    hit-message: "Hunt a wolf doesn't change your karma : &d<KARMA>"
    kill-message: "You successfully hunt the wolf : &5<KARMA>"
  Zombie:
    hit-karma-reward:      5
    hit-message: "Aim his head !"
    kill-karma-reward:    58
    kill-message: "Burn the corpse."
  ZombieVillager:
    hit-karma-reward:      0
    kill-karma-reward:  -100
```

**Comment by Rosstail** [comment]
Alright I'm back.

Your config seems good, the problem comes from me.

At the moment, put the pvp.enable as FALSE, this will fix the problem. I'll update the plugin soon, then this error will be fixed.

Put like this ^^
```yaml
pvp:
    [...]
    enable: false
```

I'm sorry for the inconvenience.
